name: Ferry Status Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pyyaml webdriver-manager

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run ferry status scraper script
        run: |
          python calmac-ferry-watch-scrapper.py

      - name: Upload output JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ferry-status-output
          path: output/calmac-ferry-status.json
